export const categories = [
  {
    id: 1,
    image: "/Category-images/neqliyyat.png",
    text: "Nəqliyyat",
    path: "",
    altcategory: [
      {
        id: 1.1,
        name: "Avtomobillər",
        path: "",
        models: [
          { id: 1.11, name: "BMW", path: "" },
          { id: 1.12, name: "Mercedes", path: "" },
          { id: 1.13, name: "Nissan", path: "" },
          { id: 1.14, name: "Toyota", path: "" },
          { id: 1.15, name: "Hyundai", path: "" },
        ],
      },
      {
        id: 1.2,
        name: "Ehtiyat hissələri",
        path: "",
        models: [
          { id: 1.21, name: "Mühərrik", path: "" },
          { id: 1.22, name: "Sürətlər qutusu", path: "" },
          { id: 1.23, name: "Asqı sistemi", path: "" },
          { id: 1.24, name: "Təkərlər və disklər", path: "" },
          { id: 1.25, name: "Elektrik avadanlığı", path: "" },
        ],
      },
      {
        id: 1.3,
        name: "Avtobuslar",
        path: "",
        models: [
          { id: 1.31, name: "Neoplan", path: "" },
          { id: 1.32, name: "Mercedes", path: "" },
          { id: 1.33, name: "Iveco", path: "" },
          { id: 1.34, name: "Setra", path: "" },
          { id: 1.35, name: "MAN", path: "" },
        ],
      },
      {
        id: 1.4,
        name: "Aqrotexnika",
        path: "",
        models: [
          { id: 1.41, name: "Belarus", path: "" },
          { id: 1.42, name: "John Deere", path: "" },
          { id: 1.43, name: "New Holland", path: "" },
          { id: 1.44, name: "Case", path: "" },
          { id: 1.45, name: "Claas", path: "" },
        ],
      },
      { id: 1.5, name: "Qeydiyyat nişanları", path: "", models: [] },
    ],
  },
  {
    id: 2,
    image: "/Category-images/ev-bag.png",
    text: "Ev və bağ üçün",
    path: "",
    altcategory: [
      {
        id: 2.1,
        name: "Mebellər",
        path: "",
        models: [
          { id: 2.11, name: "Divan", path: "" },
          { id: 2.12, name: "Kreslo", path: "" },
          { id: 2.13, name: "Masa", path: "" },
          { id: 2.14, name: "Stol", path: "" },
          { id: 2.15, name: "Dolab", path: "" },
        ],
      },
      {
        id: 2.2,
        name: "Mətbəx avadanlıqları",
        path: "",
        models: [
          { id: 2.21, name: "Soyuducu", path: "" },
          { id: 2.22, name: "Plitə", path: "" },
          { id: 2.23, name: "Mikrodalğalı", path: "" },
          { id: 2.24, name: "Qabyuyan", path: "" },
          { id: 2.25, name: "Blender", path: "" },
        ],
      },
      {
        id: 2.3,
        name: "Ev dekoru",
        path: "",
        models: [
          { id: 2.31, name: "Xalça", path: "" },
          { id: 2.32, name: "Şamdan", path: "" },
          { id: 2.33, name: "Rəsm tablo", path: "" },
          { id: 2.34, name: "Lampa", path: "" },
          { id: 2.35, name: "Pərdə", path: "" },
        ],
      },
      {
        id: 2.4,
        name: "Bağ əşyaları",
        path: "",
        models: [
          { id: 2.41, name: "Çiçək qabı", path: "" },
          { id: 2.42, name: "Bağ alətləri", path: "" },
          { id: 2.43, name: "Çəmən biçən", path: "" },
          { id: 2.44, name: "Suvarma sistemi", path: "" },
          { id: 2.45, name: "Bağ skamyası", path: "" },
        ],
      },
    ],
  },
  {
    id: 3,
    image: "/Category-images/elektronika.png",
    text: "Elektronika",
    path: "",
    altcategory: [
      {
        id: 3.1,
        name: "Telefonlar",
        path: "",
        models: [
          { id: 3.11, name: "iPhone", path: "" },
          { id: 3.12, name: "Samsung", path: "" },
          { id: 3.13, name: "Xiaomi", path: "" },
          { id: 3.14, name: "Huawei", path: "" },
          { id: 3.15, name: "Oppo", path: "" },
        ],
      },
      {
        id: 3.2,
        name: "Kompüterlər",
        path: "",
        models: [
          { id: 3.21, name: "Dell", path: "" },
          { id: 3.22, name: "HP", path: "" },
          { id: 3.23, name: "Lenovo", path: "" },
          { id: 3.24, name: "Asus", path: "" },
          { id: 3.25, name: "Acer", path: "" },
        ],
      },
      {
        id: 3.3,
        name: "Televizorlar",
        path: "",
        models: [
          { id: 3.31, name: "LG", path: "" },
          { id: 3.32, name: "Samsung", path: "" },
          { id: 3.33, name: "Sony", path: "" },
          { id: 3.34, name: "Toshiba", path: "" },
          { id: 3.35, name: "Panasonic", path: "" },
        ],
      },
      {
        id: 3.4,
        name: "Audio texnika",
        path: "",
        models: [
          { id: 3.41, name: "JBL", path: "" },
          { id: 3.42, name: "Sony", path: "" },
          { id: 3.43, name: "Bose", path: "" },
          { id: 3.44, name: "Marshall", path: "" },
          { id: 3.45, name: "Philips", path: "" },
        ],
      },
    ],
  },
  {
    id: 4,
    image: "/Category-images/usaqlar.png",
    text: "Uşaqlar aləmi",
    path: "",
    altcategory: [
      {
        id: 4.1,
        name: "Oyuncaqlar",
        path: "",
        models: [
          { id: 4.11, name: "Maşın oyuncaqları", path: "" },
          { id: 4.12, name: "Gəlinciyilər", path: "" },
          { id: 4.13, name: "Puzzle", path: "" },
          { id: 4.14, name: "LEGO", path: "" },
          { id: 4.15, name: "Top", path: "" },
        ],
      },
      {
        id: 4.2,
        name: "Uşaq geyimləri",
        path: "",
        models: [
          { id: 4.21, name: "Kofta", path: "" },
          { id: 4.22, name: "Şalvar", path: "" },
          { id: 4.23, name: "Ayaqqabı", path: "" },
          { id: 4.24, name: "Kombinezon", path: "" },
          { id: 4.25, name: "Papaq", path: "" },
        ],
      },
      {
        id: 4.3,
        name: "Uşaq arabaları",
        path: "",
        models: [
          { id: 4.31, name: "Klassik araba", path: "" },
          { id: 4.32, name: "Transformer", path: "" },
          { id: 4.33, name: "İki nəfərlik", path: "" },
          { id: 4.34, name: "Kolsok", path: "" },
          { id: 4.35, name: "Qaçış üçün araba", path: "" },
        ],
      },
    ],
  },
  {
    id: 5,
    image: "/Category-images/dasinmaz-emlak.png",
    text: "Daşınmaz əmlak",
    path: "",
    altcategory: [
      {
        id: 5.1,
        name: "Mənzillər",
        path: "",
        models: [
          { id: 5.11, name: "Yeni tikili", path: "" },
          { id: 5.12, name: "Köhnə tikili", path: "" },
          { id: 5.13, name: "Penthouse", path: "" },
          { id: 5.14, name: "Studio", path: "" },
          { id: 5.15, name: "İcarə", path: "" },
        ],
      },
      {
        id: 5.2,
        name: "Villalar və evlər",
        path: "",
        models: [
          { id: 5.21, name: "Bağ evi", path: "" },
          { id: 5.22, name: "Villa", path: "" },
          { id: 5.23, name: "Bağ kotteci", path: "" },
          { id: 5.24, name: "Bağ bağçası", path: "" },
          { id: 5.25, name: "Dacha", path: "" },
        ],
      },
      {
        id: 5.3,
        name: "Torpaq sahələri",
        path: "",
        models: [
          { id: 5.31, name: "Kənd təsərrüfatı", path: "" },
          { id: 5.32, name: "Tikinti", path: "" },
          { id: 5.33, name: "Bağ sahəsi", path: "" },
          { id: 5.34, name: "Komersiya", path: "" },
          { id: 5.35, name: "Özəl torpaq", path: "" },
        ],
      },
      {
        id: 5.4,
        name: "Ofislər",
        path: "",
        models: [
          { id: 5.41, name: "Biznes mərkəzi", path: "" },
          { id: 5.42, name: "Kommersiya ofisi", path: "" },
          { id: 5.43, name: "Ofis otaqları", path: "" },
          { id: 5.44, name: "Ko-working", path: "" },
          { id: 5.45, name: "İcarə ofis", path: "" },
        ],
      },
    ],
  },
  {
    id: 6,
    image: "/Category-images/xidmetler-biznes.png",
    text: "Xidmətlər və biznes",
    path: "",
    altcategory: [
      {
        id: 6.1,
        name: "Təmir xidməti",
        path: "",
        models: [
          { id: 6.11, name: "Usta çağırışı", path: "" },
          { id: 6.12, name: "Rəngsaz", path: "" },
          { id: 6.13, name: "Santexnik", path: "" },
          { id: 6.14, name: "Elektrik", path: "" },
          { id: 6.15, name: "Dülgər", path: "" },
        ],
      },
      {
        id: 6.2,
        name: "Təhsil kursları",
        path: "",
        models: [
          { id: 6.21, name: "İngilis dili", path: "" },
          { id: 6.22, name: "Proqramlaşdırma", path: "" },
          { id: 6.23, name: "Riyaziyyat", path: "" },
          { id: 6.24, name: "Musiqi dərsləri", path: "" },
          { id: 6.25, name: "Rəsm kursu", path: "" },
        ],
      },
      {
        id: 6.3,
        name: "Biznes avadanlıqları",
        path: "",
        models: [
          { id: 6.31, name: "Printer", path: "" },
          { id: 6.32, name: "Kassa aparatı", path: "" },
          { id: 6.33, name: "Ofis kreslosu", path: "" },
          { id: 6.34, name: "Masa", path: "" },
          { id: 6.35, name: "Server", path: "" },
        ],
      },
      {
        id: 6.4,
        name: "Maliyyə və hüquq",
        path: "",
        models: [
          { id: 6.41, name: "Mühasibatlıq", path: "" },
          { id: 6.42, name: "Vergi xidməti", path: "" },
          { id: 6.43, name: "Hüquqi məsləhət", path: "" },
          { id: 6.44, name: "Kredit məsləhəti", path: "" },
          { id: 6.45, name: "Sığorta", path: "" },
        ],
      },
    ],
  },
  {
    id: 7,
    image: "/Category-images/wexsi-esyalar.png",
    text: "Şəxsi əşyalar",
    path: "",
    altcategory: [
      {
        id: 7.1,
        name: "Geyimlər",
        path: "",
        models: [
          { id: 7.11, name: "Köynək", path: "" },
          { id: 7.12, name: "Şalvar", path: "" },
          { id: 7.13, name: "Kofta", path: "" },
          { id: 7.14, name: "Don", path: "" },
          { id: 7.15, name: "Papaq", path: "" },
        ],
      },
      {
        id: 7.2,
        name: "Ayaqqabılar",
        path: "",
        models: [
          { id: 7.21, name: "İdman ayaqqabısı", path: "" },
          { id: 7.22, name: "Ayaqqabı", path: "" },
          { id: 7.23, name: "Çəkmə", path: "" },
          { id: 7.24, name: "Sandal", path: "" },
          { id: 7.25, name: "Bot", path: "" },
        ],
      },
      {
        id: 7.3,
        name: "Saat və aksesuarlar",
        path: "",
        models: [
          { id: 7.31, name: "Kvars saat", path: "" },
          { id: 7.32, name: "Mexaniki saat", path: "" },
          { id: 7.33, name: "Üzüklər", path: "" },
          { id: 7.34, name: "Boyunbağı", path: "" },
          { id: 7.35, name: "Qolbaq", path: "" },
        ],
      },
      {
        id: 7.4,
        name: "Kosmetika",
        path: "",
        models: [
          { id: 7.41, name: "Parfüm", path: "" },
          { id: 7.42, name: "Dodaq boyası", path: "" },
          { id: 7.43, name: "Krem", path: "" },
          { id: 7.44, name: "Maskara", path: "" },
          { id: 7.45, name: "Fırça dəsti", path: "" },
        ],
      },
    ],
  },
  {
    id: 8,
    image: "/Category-images/hobbi-asude.png",
    text: "Hobbi və asudə",
    path: "",
    altcategory: [
      { id: 8.1, name: "Musiqi alətləri", path: "", models: [] },
      { id: 8.2, name: "İdman əşyaları", path: "", models: [] },
      { id: 8.3, name: "Kitablar", path: "", models: [] },
      { id: 8.4, name: "Kolleksiyalar", path: "", models: [] },
    ],
  },
  {
    id: 9,
    image: "/Category-images/heyvanlar.png",
    text: "Heyvanlar",
    path: "",
    altcategory: [
      { id: 9.1, name: "Ev heyvanları", path: "", models: [] },
      { id: 9.2, name: "Quşlar", path: "", models: [] },
      { id: 9.3, name: "Balıqlar", path: "", models: [] },
      { id: 9.4, name: "Heyvan aksesuarları", path: "", models: [] },
    ],
  },
  {
    id: 10,
    image: "/Category-images/is.png",
    text: "İş elanları",
    path: "",
    altcategory: [
      { id: 10.1, name: "Tam ştat", path: "", models: [] },
      { id: 10.2, name: "Yarım ştat", path: "", models: [] },
      { id: 10.3, name: "Freelance", path: "", models: [] },
      { id: 10.4, name: "Təcrübəçi", path: "", models: [] },
    ],
  },
];
