import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Reklam from "@/components/Reklam";
import Footer from "@/components/Footer";
import MobileFooter from "@/components/MobileFooter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Tap.az - Pulsuz Elanlar Saytı",
  description: "Generated by create next app",
  icons:{
    icon:"/favicon.png"
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header/>
        <div className="fixed left-0 h-full">
          <Reklam />
        </div>
         <div className="fixed right-0 h-full">
          <Reklam />
        </div>
        <div className="mx-0 md:mx-[13vw] md:p-5">
          {children}
        </div>
        <Footer/>
        <MobileFooter />
      </body>
    </html>
  );
}
